### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by EndarValuk** [codecentric/dotnet_gitlab_code_quality#1]
Can u add support for .net 6? Cause its an LTS release, it would be wonderfult to have such a nice tool in hand.

**Comment by ChristianSauer** [comment]
Hi Endar, I would welcome a PR for this.

**Comment by dannyvolders** [comment]
https://github.com/codecentric/dotnet_gitlab_code_quality/pull/3

**Comment by ChristianSauer** [comment]
Thanks and closed
