### ISSUE TITLE
Error: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by calicoder77** [codecentric/dotnet_gitlab_code_quality#2]
Good day, anyone else run into this error _System.NullReferenceException: Object reference not set to an instance of an object_ running this command?

dotnet cq sarif codeanalysis.1-0.sarif codeanalysis.gitlab.1-0.sarif.json c:\dev

```
We currently assume that the given Sarif v1.0, Sarif 2.0 is not supported
Could not convert {"SarifNodeKindVersionOne": "ResultVersionOne", "RuleId": "C26451", "RuleKey": null, "Level": "Default", "Message": "Arithmetic overflow: Using operator '+'
on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).",
"FormattedRuleMessage": null, "Locations": [{"SarifNodeKindVersionOne": "LocationVersionOne", "AnalysisTarget": null, "ResultFile": {"SarifNodeKindVersionOne":
"PhysicalLocationVersionOne", "Uri": null, "UriBaseId": null, "Region": {"SarifNodeKindVersionOne": "RegionVersionOne", "StartLine": 86, "StartColumn": 65, "EndLine": 86,
"EndColumn": 77, "Offset": 0, "Length": 0, "$type": "RegionVersionOne"}, "$type": "PhysicalLocationVersionOne"}, "FullyQualifiedLogicalName": null,
"LogicalLocationKey": null, "DecoratedName": null, "PropertyNames": [], "Tags": [], "$type": "LocationVersionOne"}], "Snippet": null, "Id": null, "ToolFingerprintContribution"
: null, "Stacks": null, "CodeFlows": null, "RelatedLocations": null, "SuppressionStates": "None", "BaselineState": "None", "Fixes": null, "PropertyNames": [], "Tags": [],
"$type": "ResultVersionOne"}, skipping

System.NullReferenceException: Object reference not set to an instance of an object.
   at CodeQualityToGitlab.SarifConverter.GetPath(String pathRoot, LocationVersionOne begin) in
	/home/runner/work/dotnet_gitlab_code_quality/dotnet_gitlab_code_quality/CodeQualityToGitlab/SarifConverter.cs:line 64
   at CodeQualityToGitlab.SarifConverter.ConvertToCodeQualityRaw(FileInfo source, String pathRoot) in
	/home/runner/work/dotnet_gitlab_code_quality/dotnet_gitlab_code_quality/CodeQualityToGitlab/SarifConverter.cs:line 35
```

**Comment by ChristianSauer** [comment]
Hi, can I have the original sarif or a ideally a small repro sarif file? Will take a look

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
From: calicoder77 ***@***.***>
Sent: Friday, March 31, 2023 6:21:06 PM
To: codecentric/dotnet_gitlab_code_quality ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [codecentric/dotnet_gitlab_code_quality] Error: System.NullReferenceException: Object reference not set to an instance of an object. (Issue #2)


Good day, anyone else run into this error System.NullReferenceException: Object reference not set to an instance of an object running this command?

dotnet cq sarif codeanalysis.1-0.sarif codeanalysis.gitlab.1-0.sarif.json c:\dev

We currently assume that the given Sarif v1.0, Sarif 2.0 is not supported
Could not convert {"SarifNodeKindVersionOne": "ResultVersionOne", "RuleId": "C26451", "RuleKey": null, "Level": "Default", "Message": "Arithmetic overflow: Using operator '+'
on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).",
"FormattedRuleMessage": null, "Locations": [{"SarifNodeKindVersionOne": "LocationVersionOne", "AnalysisTarget": null, "ResultFile": {"SarifNodeKindVersionOne":
"PhysicalLocationVersionOne", "Uri": null, "UriBaseId": null, "Region": {"SarifNodeKindVersionOne": "RegionVersionOne", "StartLine": 86, "StartColumn": 65, "EndLine": 86,
"EndColumn": 77, "Offset": 0, "Length": 0, "$type": "RegionVersionOne"}, "$type": "PhysicalLocationVersionOne"}, "FullyQualifiedLogicalName": null,
"LogicalLocationKey": null, "DecoratedName": null, "PropertyNames": [], "Tags": [], "$type": "LocationVersionOne"}], "Snippet": null, "Id": null, "ToolFingerprintContribution"
: null, "Stacks": null, "CodeFlows": null, "RelatedLocations": null, "SuppressionStates": "None", "BaselineState": "None", "Fixes": null, "PropertyNames": [], "Tags": [],
"$type": "ResultVersionOne"}, skipping

System.NullReferenceException: Object reference not set to an instance of an object.
   at CodeQualityToGitlab.SarifConverter.GetPath(String pathRoot, LocationVersionOne begin) in
        /home/runner/work/dotnet_gitlab_code_quality/dotnet_gitlab_code_quality/CodeQualityToGitlab/SarifConverter.cs:line 64
   at CodeQualityToGitlab.SarifConverter.ConvertToCodeQualityRaw(FileInfo source, String pathRoot) in
        /home/runner/work/dotnet_gitlab_code_quality/dotnet_gitlab_code_quality/CodeQualityToGitlab/SarifConverter.cs:line 35

**Comment by calicoder77** [comment]
Thanks for the quick reply, here's the file:

```
{
  "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-1.0.0.json",
  "version": "1.0.0",
  "runs": [
    {
      "tool": {
        "name": "PREfast",
        "fullName": "PREfast Code Analysis",
        "version": "14.29.30148.0",
        "language": "en-US"
      },
      "invocation": {
        "commandLine": "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\c1xx.dll\" ...
      },
      "files": {
        "file:///c:/dev/app/stdafx.cpp": {
          "hashes": [
            {
              "value": "72febd207eaaf204298b40f071737e0c",
              "algorithm": "unknown"
            }
          ]
        }
      },
      "results": []
    },
    {
      "tool": {
        "name": "PREfast",
        "fullName": "PREfast Code Analysis",
        "version": "14.29.30148.0",
        "language": "en-US"
      },
      "invocation": {
        "commandLine": "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\c1xx.dll\" ...
      },
      "files": {
        "file:///c:/dev/app/mainApp.cpp": {
          "hashes": [
            {
              "value": "6f448b3da75733e7b8e86ef60c97894e",
              "algorithm": "unknown"
            }
          ]
        }
      },
      "results": [
        {
          "ruleId": "C26451",
          "message": "Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).",
          "locations": [
            {
              "resultFile": {
                "region": {
                  "startLine": 86,
                  "startColumn": 65,
                  "endLine": 86,
                  "endColumn": 77
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by ChristianSauer** [comment]
I am pusing Version 0.5.0 which mitigates this. Cq will no longer break, but the issue is more with the generating tool than Cq.
Your 'result.locations[0].resultFile.region` lacks an 'uri', which should be there.
I am now logging an Error and add a dummy file location but ideally your tool should add that uri, because otherwise there is no way to identify the file.

**Comment by calicoder77** [comment]
Thank you for the quick fix. I'm using MS Build cl.exe analyze to create the SARIF file. It only supports 2.1 from what I see and have to use the Microsoft Sarif SDK converter tool to make it a SARIF 1.0 file which is what I feed to cq. I'll dig deeper into this and post an update if I find anything. Thanks

**Comment by ChristianSauer** [comment]
Hey, if you have a 2.1 file for me we can add it's i have no tools which emit 2 so I couldn't add it.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by calicoder77** [comment]
Sure, I can add a test SARIF 2.1 file here

**Comment by calicoder77** [comment]
Here's a SARIF 2.1 sample file I use from the Sarif SDK project

```
{
  "version": "2.1.0",
  "$schema": "http://json.schemastore.org/sarif-2.1.0-rtm.4",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "ESLint",
          "informationUri": "https://eslint.org",
          "rules": [
            {
              "id": "no-unused-vars",
              "shortDescription": {
                "text": "disallow unused variables"
              },
              "helpUri": "https://eslint.org/docs/rules/no-unused-vars",
              "properties": {
                "category": "Variables"
              }
            }
          ]
        }
      },
      "artifacts": [
        {
          "location": {
            "uri": "file:///C:/dev/sarif/sarif-tutorials/samples/Introduction/simple-example.js"
          }
        }
      ],
      "results": [
        {
          "level": "error",
          "message": {
            "text": "'x' is assigned a value but never used."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///C:/dev/sarif/sarif-tutorials/samples/Introduction/simple-example.js",
                  "index": 0
                },
                "region": {
                  "startLine": 1,
                  "startColumn": 5
                }
              }
            }
          ],
          "ruleId": "no-unused-vars",
          "ruleIndex": 0
        }
      ]
    }
  ]
}

```

**Comment by ChristianSauer** [comment]
Took a long time but should be in 1.0.0

**Comment by calicoder77** [comment]
> Took a long time but should be in 1.0.0

Thank you so much
