### ISSUE TITLE
Skip result when suppressionStates is not empty/missing

### ISSUE THREAD

**Issue by mpidash** [codecentric/dotnet_gitlab_code_quality#4]
Currently, if a result is suppressed (i.e. `suppresionStates` is not empty or missing), it is still converted to a code quality issue.

These results are generated when you suppress a warning with `SuppressMessageAttribute` or use a preprocessor directive (`#pragma warning disable ...`).
Auto generated code from `RazorSourceGenerator` also suppress warnings this way (as seen in `codeanalysis.sarif3.json` where the `suppressionStates` is not empty).

I would suggest that results are skipped if `SuppressionStates` is not `SuppressionStatesVersionOne.None`.
~I can prepare a PR if you want.~ See #5.

**Comment by ChristianSauer** [comment]
Thankls, that took waay to long to merge, Sorry!
